name: Publish and Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry

      - name: Check lock file
        run: poetry lock --check

      - name: Install dependencies
        run: poetry install --sync

      - name: Test
        run: poetry run pytest

      - name: Build
        run: poetry build

      - name: Set module version
        id: module
        run: echo "version=$(poetry version --short)" >> $GITHUB_OUTPUT

      - name: Publish to PyPI
        if: github.ref_type == 'tag' && github.ref_name == steps.module.outputs.version
        run: |
          poetry config repo.test_pypi $POETRY_REPOSITORIES_TEST_PYPI
          poetry publish -r test_pypi
        env:
          POETRY_REPOSITORIES_TEST_PYPI: https://test.pypi.org/legacy/

      - name: Github release
        if: github.ref_type == 'tag' && github.ref_name == steps.module.outputs.version
        uses: softprops/action-gh-release@v1
        with:
          files: dist/
